const  nums =[33,15,81,90]
const mult3 = nums.map(a => a *3)
console.log("OS múltiplos dos numeros dados são : "+mult3)
const div3 =nums.map(a=>a/3)
console.log("Os dividendos dos números dados são: "+div3)
const soma3 =nums.map(a=>a+3)
console.log("A soma dos números dados são: "+soma3)
const subtr3 =nums.map(a=>a-3)
console.log("A subtração dos números dados são: "+subtr3)
const expoent3 =nums.map(a=>a**3)
console.log("Os expoentes dos números dados são: "+expoent3)
